spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orquestro_db
    username: orquestro_admin
    password: orquestro_secure_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

application:
  security:
    jwt:
      # Chave de teste para desenvolvimento
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 24h
      refresh-token-expiration: 604800000 # 7 days

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: INFO

  management:
    endpoints:
      web:
        exposure:
          include: health, info, metrics, env 
    endpoint:
      health:
        show-detail: always